### ISSUE TITLE
Can't save multiple filters in single criteria entry

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Calypso#10]
I'm attempting to create an inclusion rule in Calypso. I added a "New Criteria" for Observation Period, and then added 2 filters within that criteria rule (duration and start date). When I saved, the user interface only showed the 1 filter criteria (duration).  The start date filter disappeared.

**Comment by chrisknoll** [comment]
Checked on this, seems to be saving to the DB properly, but not deserializing right onto the javascript side.  Probably in the client side javascript lib.  Will work on a fix.

**Comment by anthonysena** [comment]
Looks good now with that fix in place. I'll close this out. Thanks!
